name: env-demo

on:
  push:

jobs:
  set-env:
    runs-on: ubuntu-latest
    env:
      DEPLOY_ENV: staging

    steps:
      - name: Display Environment Variable # Nível 1
        run: |
          echo "A variável DEPLOY_ENV está configurada como: ${{ env.DEPLOY_ENV }}"
