name: 2.3 Secrets Demo

on:
  push:

jobs:
  use-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Display Secret (Mascara o valor)
        # O segredo Ã© injetado via secrets.NOME_DO_SEGREDO
        run: |
          echo "Tentando usar o segredo: ${{ secrets.MY_SECRET }}"


